In [4]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('cardio_dataset.csv').values

data=dataset[:,0:7]
target=dataset[:,7]

target=np.reshape(target, (-1,1))

print(data[:10])
print(target[:10])
print('size of the dataset:',len(dataset))

[[  1.  48. 236.  66.   0.   1.   0.]
 [  0.  48. 260.  51.   0.   1.   1.]
 [  0.  44. 187.  49.   1.   1.   0.]
 [  1.  42. 216.  57.   1.   1.   0.]
 [  1.  56. 156.  42.   0.   1.   0.]
 [  0.  44. 162.  57.   1.   1.   0.]
 [  0.  50. 244.  47.   0.   1.   0.]
 [  0.  48. 212.  30.   1.   1.   0.]
 [  1.  66. 202.  53.   0.   1.   1.]
 [  0.  63. 186.  46.   1.   1.   0.]]
[[ 1.1]
 [ 7. ]
 [ 7. ]
 [ 0.4]
 [ 2.2]
 [ 3. ]
 [ 4.2]
 [17.4]
 [13.4]
 [17.3]]
size of the dataset: 6644


In [5]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [6]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(train_data,train_target)
predicted_target=model.predict(test_data)

In [7]:
from sklearn.metrics import r2_score

r2=r2_score(test_target,predicted_target)
print("r2 score:",r2)

r2 score: 0.7718590687666014


In [8]:
print('Actual Target:',test_target[:10].T)
print('Predicted Target:',predicted_target[:10].T)

Actual Target: [[16.1  2.2  4.7  9.4  6.5 30.4 34.8  9.3  8.3  6.3]]
Predicted Target: [[17.05022002  1.47986679  5.21867467 12.65626301  4.5268223  23.5332322
  31.77634304 15.87200172 13.89925405  5.28103092]]


In [9]:
import joblib

joblib.dump(model,'heart_risk_predict_regression_model.sav')

['heart_risk_predict_regression_model.sav']